import axios from 'axios';

const USER_LOGIN = 'USER_LOGIN';
const USER_REGISTER = 'USER_REGISTER';
const SURE_REQUEST = 'SURE_REQUEST';
const FETCHING = 'FETCHING';
const VAULT = "VAULTING";
const URL = "http:127.0.0.1:8080/";
const MESSAGE = 'MESSAGE';
const REQUEST_STATUS = 'REQUEST_STATUS';
const PLACES = 'PLACES';
const COUNTRIES = 'COUNTRIES';
const STATES = 'STATES';
const USERBASICDETAILS = 'USERBASICDETAILS';
const USERHOMEADDRESS = 'USERHOMEADDRESS';
const USEROFFICEADDRESS = 'USEROFFICEADDRESS';
const USERMEDIAACCOUNT = 'USERMEDIAACCOUNT';
const MAKEREQUEST = 'MAKEREQUEST';
const PENDINGAPPROVALS = 'PENDINGAPPROVALS';
const REJECTLOANREQUEST = 'REJECTLOANREQUEST';
const LOANTOBEDISBURSED = 'LOANTOBEDISBURSED';
const GETPROFILE = 'GETPROFILE';
const GETVAULT = 'GETVAULT';
const APPROVEDLOANS = 'APPROVEDLOANS';
const DISBURSEDLOANS = 'DISBURSEDLOANS';
const TOBEDISBURSED = 'TOBEDISBURSED';
const UPDATESUREDEAL = 'UPDATESUREDEAL';
const LOANSDISBURSED = 'LOANSDISBURSED';
const MYAPPROVEDLOANS = 'MYAPPROVEDLOANS';
const MYPENDINGAPPROVALLOANS = 'MYPENDINGAPPROVALLOANS';
const ANALYTICS = 'ANALYTICS';
const COMPLETEUSERPROFILE = 'COMPLETEUSERPROFILE';
const NEXTPHASE = 'NEXTPHASE';
const USERBANKINFORMATION = 'USERBANKINFORMATION';
const MYVAULT = 'MYVAULT';
const MYVAULTTRANSACTIONS = 'MYVAULTTRANSACTIONS';
const AVAILABLEFUND = 'AVAILABLEFUND';
const REQUESTAMOUNT = 'REQUESTAMOUNT';
const INTEREST = 'INTEREST';
const LOANTENOR = 'LOANTENOR';
const BORROWER = 'BORROWER';
const OTHERS = 'OTHERS';
const PLACES_RESET = 'PLACES_RESET';
const CREATEVAULT_RESET= 'CREATEVAULT_RESET';
const MAIN_RESET= 'MAIN_RESET';
const ALLLOANSREQUEST = 'ALLLOANSREQUEST';
const REPAYMENT_LENDER = 'REPAYMENT_LENDER';
const REPAYMENT_BORROWER = 'REPAYMENT_BORROWER';
const VIEWREPAYMENTONREQUESTID = 'VIEWREPAYMENTONREQUESTID';
const ALL_LENDER_OFFERS= 'ALL_LENDER_OFFERS';
const ALL_BORROWER_REQUESTS = 'ALL_BORROWER_REQUESTS';
const CONNECTWITHBORROWER = 'CONNECTWITHBORROWER';


const INSTANCE = axios.create({
    baseURL: URL,
    timeout: 20000,
    headers: {
      'Content-Type': 'Application/json',
      'Accept': 'application/json'
    }
});

const AUTHINSTANCE = axios.create({
  baseURL: URL,
  timeout: 20000,
  headers: {
    'Content-Type': 'Application/json',
    'Accept': 'application/json',
    'Authorization': `Bearer ${sessionStorage.getItem('token')}`
  }
});


export
{
    USER_LOGIN,
    USER_REGISTER,
    SURE_REQUEST,
    FETCHING,
    VAULT,
    PLACES,
    MESSAGE,
    REQUEST_STATUS,
    INSTANCE,
    AUTHINSTANCE,
    COUNTRIES,
    STATES,
    USERBASICDETAILS,
    USERHOMEADDRESS,
    USEROFFICEADDRESS,
    USERMEDIAACCOUNT,
    MAKEREQUEST,
    PENDINGAPPROVALS,
    REJECTLOANREQUEST,
    LOANTOBEDISBURSED,
    GETPROFILE,
    GETVAULT,
    APPROVEDLOANS,
    DISBURSEDLOANS,
    TOBEDISBURSED,
    UPDATESUREDEAL,
    LOANSDISBURSED,
    MYAPPROVEDLOANS,
    MYPENDINGAPPROVALLOANS,
    ANALYTICS,
    COMPLETEUSERPROFILE,
    NEXTPHASE,
    USERBANKINFORMATION,
    MYVAULT,
    MYVAULTTRANSACTIONS,
    AVAILABLEFUND,
    REQUESTAMOUNT,
    INTEREST,
    LOANTENOR,
    BORROWER,
    OTHERS,
    PLACES_RESET,
    CREATEVAULT_RESET,
    MAIN_RESET,
    ALLLOANSREQUEST,
    REPAYMENT_LENDER,
    REPAYMENT_BORROWER,
    VIEWREPAYMENTONREQUESTID,
    ALL_LENDER_OFFERS,
    ALL_BORROWER_REQUESTS,
    CONNECTWITHBORROWER
};