import axios from 'axios';

const USER_LOGIN = 'USER_LOGIN';
const USER_REGISTER = 'USER_REGISTER';
const SURE_REQUEST = 'SURE_REQUEST';
const FETCHING = 'FETCHING';
const VAULT = "VAULTING";
const PATH = "http://localhost:8000/api/";
//const IMAGEPATH = "http://localhost/surebankermoney/public";
//const PATH = 'http://surebanker.online/surebanker/api/';
const MESSAGE = 'MESSAGE';
const REQUEST_STATUS = 'REQUEST_STATUS';
const PLACES = 'PLACES';
const COUNTRIES = 'COUNTRIES';
const STATES = 'STATES';
const USERBASICDETAILS = 'USERBASICDETAILS';
const USERHOMEADDRESS = 'USERHOMEADDRESS';
const USEROFFICEADDRESS = 'USEROFFICEADDRESS';
const USERMEDIAACCOUNT = 'USERMEDIAACCOUNT';
const MAKEREQUEST = 'MAKEREQUEST';
const PENDINGAPPROVALS = 'PENDINGAPPROVALS';
const REJECTLOANREQUEST = 'REJECTLOANREQUEST';
const LOANTOBEDISBURSED = 'LOANTOBEDISBURSED';
const GETPROFILE = 'GETPROFILE';
const GETVAULT = 'GETVAULT';
const APPROVEDLOANS = 'APPROVEDLOANS';
const DISBURSEDLOANS = 'DISBURSEDLOANS';
const TOBEDISBURSED = 'TOBEDISBURSED';
const UPDATESUREDEAL = 'UPDATESUREDEAL';
const LOANSDISBURSED = 'LOANSDISBURSED';
const MYAPPROVEDLOANS = 'MYAPPROVEDLOANS';
const MYPENDINGAPPROVALLOANS = 'MYPENDINGAPPROVALLOANS';
const ANALYTICS = 'ANALYTICS';
const COMPLETEUSERPROFILE = 'COMPLETEUSERPROFILE';
const NEXTPHASE = 'NEXTPHASE';
const USERBANKINFORMATION = 'USERBANKINFORMATION';
const MYVAULT = 'MYVAULT';
const MYVAULTTRANSACTIONS = 'MYVAULTTRANSACTIONS';
const AVAILABLEFUND = 'AVAILABLEFUND';
const REQUESTAMOUNT = 'REQUESTAMOUNT';
const INTEREST = 'INTEREST';
const LOANTENOR = 'LOANTENOR';
const BORROWER = 'BORROWER';
const OTHERS = 'OTHERS';
const PLACES_RESET = 'PLACES_RESET';
const CREATEVAULT_RESET= 'CREATEVAULT_RESET';
const MAIN_RESET= 'MAIN_RESET';
const ALLLOANSREQUEST = 'ALLLOANSREQUEST';
const REPAYMENT_LENDER = 'REPAYMENT_LENDER';
const REPAYMENT_BORROWER = 'REPAYMENT_BORROWER';
const VIEWREPAYMENTONREQUESTID = 'VIEWREPAYMENTONREQUESTID';
const ALL_LENDER_OFFERS= 'ALL_LENDER_OFFERS';
const ALL_BORROWER_REQUESTS = 'ALL_BORROWER_REQUESTS';
const CONNECTWITHBORROWER = 'CONNECTWITHBORROWER';
const BORROWER_OVERDUES = 'BORROWER_OVERDUES';
const LENDER_OVERDUES = 'LENDER_OVEDUES';
const LOANSRECEIVED = 'LOANSRECEIVED';
const BORROWER_PAYMENT_SCHEDULES = 'BORROWER_PAYMENT_SCHEDULES';
const LENDER_PAYMENT_SCHEDULES = 'LENDER_PAYMENT_SCHEDULES';
const VERIFY_EMAIL = 'VERIFY_EMAIL';
const VERIFY_PHONE = 'VERIFY_PHONE';
const CODES = 'CODES';
const CITIES = 'CITIES';
const VAULT_CREATED  = 'VAULT_CREATED';
const SURECONNECT = 'SURECONNECT';
const PAYMENTANALYTICS = 'PAYMENTANALYTICS';
const LOGOUT = 'LOGOUT';
const SUCCESSCOLOR = 'green';
const ERRORCOLOR = 'red';
const BANKS = 'BANKS';
const PAYSTACK_APIKEY = 'pk_test_20f82f24ab9e053d65cc58c7fabdc72c90fee340';
const CREDIT_REGISTRY_LOGIN = 'CREDIT_REGISTRY_LOGIN';
const CREDIT_REGISTRY_REPORT = 'CREDIT_REGISTRY_REPORT';
const WITHDRAWFROMREPAYMENT = 'WITHDRAWFROMREPAYMENT';
const IMAGEPATH = "http://localhost:8000/files/";


const INSTANCE = axios.create({
    baseURL: URL,
    timeout: 20000,
    headers: {
      'Content-Type': 'Application/json',
      'Accept': 'application/json'
    }
});

const AUTHINSTANCE = axios.create({
  baseURL: URL,
  timeout: 20000,
  headers: {
    'Content-Type': 'Application/json',
    'Accept': 'application/json',
    'Authorization': `Bearer ${sessionStorage.getItem('token')}`
  }
});


export
{
    USER_LOGIN,
    USER_REGISTER,
    SURE_REQUEST,
    FETCHING,
    VAULT,
    PLACES,
    MESSAGE,
    REQUEST_STATUS,
    INSTANCE,
    AUTHINSTANCE,
    COUNTRIES,
    STATES,
    USERBASICDETAILS,
    USERHOMEADDRESS,
    USEROFFICEADDRESS,
    USERMEDIAACCOUNT,
    MAKEREQUEST,
    PENDINGAPPROVALS,
    REJECTLOANREQUEST,
    LOANTOBEDISBURSED,
    GETPROFILE,
    GETVAULT,
    APPROVEDLOANS,
    DISBURSEDLOANS,
    TOBEDISBURSED,
    UPDATESUREDEAL,
    LOANSDISBURSED,
    MYAPPROVEDLOANS,
    MYPENDINGAPPROVALLOANS,
    ANALYTICS,
    COMPLETEUSERPROFILE,
    NEXTPHASE,
    USERBANKINFORMATION,
    MYVAULT,
    MYVAULTTRANSACTIONS,
    AVAILABLEFUND,
    REQUESTAMOUNT,
    INTEREST,
    LOANTENOR,
    BORROWER,
    OTHERS,
    PLACES_RESET,
    CREATEVAULT_RESET,
    MAIN_RESET,
    ALLLOANSREQUEST,
    REPAYMENT_LENDER,
    REPAYMENT_BORROWER,
    VIEWREPAYMENTONREQUESTID,
    ALL_LENDER_OFFERS,
    ALL_BORROWER_REQUESTS,
    CONNECTWITHBORROWER,
    BORROWER_OVERDUES,
    LENDER_OVERDUES,
    LOANSRECEIVED,
    BORROWER_PAYMENT_SCHEDULES,
    LENDER_PAYMENT_SCHEDULES,
    VERIFY_EMAIL,
    PATH,
    VERIFY_PHONE,
    CODES,
    CITIES,
    VAULT_CREATED,
    SURECONNECT,
    PAYMENTANALYTICS,
    LOGOUT,
    SUCCESSCOLOR,
    ERRORCOLOR,
    BANKS,
    PAYSTACK_APIKEY,
    CREDIT_REGISTRY_LOGIN,
    CREDIT_REGISTRY_REPORT,
    WITHDRAWFROMREPAYMENT,
    IMAGEPATH
};